<?php

namespace ContainerSDkbU0o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ir1HULyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ir1HULy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ir1HULy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.KksGd9j', 'get_ServiceLocator_KksGd9jService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.KksGd9j', 'get_ServiceLocator_KksGd9jService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::new' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\VideoController::delete' => ['privates', '.service_locator.5wcf_NW', 'get_ServiceLocator_5wcfNWService', true],
            'App\\Controller\\VideoController::edit' => ['privates', '.service_locator.5wcf_NW', 'get_ServiceLocator_5wcfNWService', true],
            'App\\Controller\\VideoController::index' => ['privates', '.service_locator.PtWQQD8', 'get_ServiceLocator_PtWQQD8Service', true],
            'App\\Controller\\VideoController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VideoController::show' => ['privates', '.service_locator.Kdg6TWc', 'get_ServiceLocator_Kdg6TWcService', true],
            'App\\Controller\\VideoController::showShoesByStatus' => ['privates', '.service_locator.5DN8wnM', 'get_ServiceLocator_5DN8wnMService', true],
            'App\\Controller\\VideoController::updateStatus' => ['privates', '.service_locator.5DN8wnM', 'get_ServiceLocator_5DN8wnMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.KksGd9j', 'get_ServiceLocator_KksGd9jService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.KksGd9j', 'get_ServiceLocator_KksGd9jService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:new' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.478xwl1', 'get_ServiceLocator_478xwl1Service', true],
            'App\\Controller\\VideoController:delete' => ['privates', '.service_locator.5wcf_NW', 'get_ServiceLocator_5wcfNWService', true],
            'App\\Controller\\VideoController:edit' => ['privates', '.service_locator.5wcf_NW', 'get_ServiceLocator_5wcfNWService', true],
            'App\\Controller\\VideoController:index' => ['privates', '.service_locator.PtWQQD8', 'get_ServiceLocator_PtWQQD8Service', true],
            'App\\Controller\\VideoController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\VideoController:show' => ['privates', '.service_locator.Kdg6TWc', 'get_ServiceLocator_Kdg6TWcService', true],
            'App\\Controller\\VideoController:showShoesByStatus' => ['privates', '.service_locator.5DN8wnM', 'get_ServiceLocator_5DN8wnMService', true],
            'App\\Controller\\VideoController:updateStatus' => ['privates', '.service_locator.5DN8wnM', 'get_ServiceLocator_5DN8wnMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::new' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\VideoController::delete' => '?',
            'App\\Controller\\VideoController::edit' => '?',
            'App\\Controller\\VideoController::index' => '?',
            'App\\Controller\\VideoController::new' => '?',
            'App\\Controller\\VideoController::show' => '?',
            'App\\Controller\\VideoController::showShoesByStatus' => '?',
            'App\\Controller\\VideoController::updateStatus' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:new' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\VideoController:delete' => '?',
            'App\\Controller\\VideoController:edit' => '?',
            'App\\Controller\\VideoController:index' => '?',
            'App\\Controller\\VideoController:new' => '?',
            'App\\Controller\\VideoController:show' => '?',
            'App\\Controller\\VideoController:showShoesByStatus' => '?',
            'App\\Controller\\VideoController:updateStatus' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
