<?php

namespace Container1Kzmk3y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5wcfNWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5wcf_NW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5wcf_NW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'video' => ['privates', '.errored..service_locator.5wcf_NW.App\\Entity\\Video', NULL, 'Cannot autowire service ".service_locator.5wcf_NW": it references class "App\\Entity\\Video" but no such service exists.'],
            'videoRepository' => ['privates', 'App\\Repository\\VideoRepository', 'getVideoRepositoryService', true],
        ], [
            'video' => 'App\\Entity\\Video',
            'videoRepository' => 'App\\Repository\\VideoRepository',
        ]);
    }
}
